config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :comments, module: :questions
    resources :answers
  end

  resources :answers do
    resources :comments, module: :answers
  end

  post '/questions/:id/answers/:answer_id/choose', to: 'questions#choose', as: 'choose_question_answer'

  post '/questions/:id/upvote', to: 'questions#upvote', as: 'upvote_question'
  post '/questions/:id/downvote', to: 'questions#downvote', as: 'downvote_question'

  post '/answers/:id/upvote', to: 'answers#upvote', as: 'upvote_answer'
  post '/answers/:id/downvote', to: 'answers#downvote', as: 'downvote_answer'

  devise_for :users
  get 'home/index'
  root 'questions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :answers
  has_one :chosen_answer, -> { where(chosen: true) }, class_name: 'Answer'

  accepts_nested_attributes_for :answers, update_only: true

  validates :title, :body, presence: true
  validates_associated :user
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Question.find(params[:question_id])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :choose]
  before_action :authenticate_user!, :except => [:index, :show]

  # GET /questions
  # GET /questions.json
  def index
    # @questions = Question.all
    # @latest = @questions.reverse
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true)
    @pagy, @highest = pagy(@questions.order(cached_votes_score: :desc))
    # @open
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  def choose
    answer = Answer.find_by(id: params[:answer_id])

    if answer.chosen
      answer.chosen = false
    elsif @question.chosen_answer === nil
      answer.chosen = true
    else
      @question.chosen_answer.chosen = false
      answer.chosen = true
      @question.chosen_answer.save
    end
    answer.save # necessary?
    redirect_to @question
  end

  def upvote
    if current_user.voted_as_when_voted_for @question # if user has liked this question, unlike it
      @question.unliked_by current_user
    else
      @question.liked_by current_user # otherwise, like it
    end
    redirect_to @question
  end

  def downvote
    unless (current_user.voted_as_when_voted_for @question) === false # if user has disliked it, undislike it
      @question.disliked_by current_user
    else # if user has not liked nor disliked, dislike it
      @question.undisliked_by current_user
    end
    redirect_to @question
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.answered = false
    @question.user_id = current_user.id

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :body, answers_attributes: [:id])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true, html: { class: "question-form" }) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field title">
    <%= form.label :título %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="field body">
    <%= form.label :corpo %>
    <%= form.text_area :body, required: true %>
  </div>

  <% if false %>

    <div class="field">
      <%= form.label :score %>
      <%= form.number_field :score %>
    </div>

    <div class="field">
      <%= form.label :answered %>
      <%= form.check_box :answered %>
    </div>

  <% end %>

  <%= link_to "Como fazer uma boa pergunta (stack overflow)", "https://stackoverflow.com/help/how-to-ask"%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Perguntas</h1>

<br>

<% @highest.each do |q| %>
  <div class="container-fluid no-gutters question-short">
    <div class="row">
      <div class="col-1 question-engagement">
          <h3><%= q.cached_votes_score %></h3>
          <%= q.cached_votes_score === 1 ? "Voto" : "Votos" %> <%# pluralização correta %>
      </div>

      <div class="col-1 question-engagement <%= (q.chosen_answer === nil) ? "" : "answered" %>">
        <h3><%= q.answers.size %></h3>
        <%= q.answers.size === 1 ? "Resposta" : "Respostas" %> <%# pluralização correta %>
      </div>

      <div class="col-6 question-body">
        <h4><%= link_to q.title, q %></h4>
      </div>

      <div class="col-4 question-author">
        perguntado em <%= q.created_at %>
          <br>
          <span class="text-primary">
            <%= q.user.email %>
          </span>
          <%= "- #{q.user.major} (#{q.user.year}.#{q.user.semester})" %>
      </div>
    </div>
  </div>
<% end %>

<%== pagy_nav(@pagy) %>

<br>

<%= link_to 'New Question', new_question_path %> |

<% if user_signed_in? %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/questions/new.html.erb
<h1>Nova Pergunta</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="pb-2 mt-4 mb-2 header">
  <h1><%= @question.title %></h1>
</div>

<div class="container-fluid no-gutters question-long">
  <div class="row">
    <div class="col-1">
      <div class="container score">
        <%= render 'layouts/score', votable: @question %>
      </div>
    </div>
    <div class="col-7 question-body">
      <div class="row">
        <%= simple_format(@question.body) %>
      </div>
      <div class="row justify-content-end">
        <div class="col-5 question-author">
          perguntado em <%= @question.created_at %>
          <br>
          <span class="text-primary">
            <%= @question.user.email %>
          </span>
          <%= "- #{@question.user.major} (#{@question.user.year}.#{@question.user.semester})" %>
        </div>
      </div>
    </div>
    <div class="col-4 question-comments">
      <%# comments on this question %>
      <%= render 'comments/comments', commentable: @question %>
    </div>
  </div>
</div>

<%# answers to this question %>
<%= render 'answers/answers', question: @question %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>