config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :comments, module: :questions
    resources :answers
  end

  resources :answers do
    resources :comments, module: :answers
  end

  post '/questions/:id/answers/:answer_id/choose', to: 'questions#choose', as: 'choose_question_answer'

  post '/questions/:id/upvote', to: 'questions#upvote', as: 'upvote_question'
  post '/questions/:id/downvote', to: 'questions#downvote', as: 'downvote_question'

  post '/answers/:id/upvote', to: 'answers#upvote', as: 'upvote_answer'
  post '/answers/:id/downvote', to: 'answers#downvote', as: 'downvote_answer'

  devise_for :users
  get 'home/index'
  root 'questions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true
  validates_associated :user, :commentable
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Answer.find(params[:answer_id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user
    # @comment.commentable_id = params.question_id
    session[:return_to] ||= request.referer

    respond_to do |format|
      if @comment.save
        format.html { redirect_to session.delete(:return_to), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :commentable_type, :question_id, :answer_id)
    end
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Question.find(params[:question_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.erb
<ul class="comments">
  <% commentable.comments.reverse.each do |comment| %>
    <li>
      <%= comment.body %>
      -
      <span class="text-primary"><%= comment.user.email %></span>
    </li>
  <% end %>
</ul>
<%# create new comment on this question %>
<%= render 'comments/form', commentable: commentable %>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new], html: { autocomplete: "off" } do |f| %>
  <div class="field">
    <%= f.text_field :body, placeholder: "Comentar", class: "new-comment", required: true %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_question_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>