config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :comments, module: :questions
    resources :answers
  end

  resources :answers do
    resources :comments, module: :answers
  end

  post '/questions/:id/answers/:answer_id/choose', to: 'questions#choose', as: 'choose_question_answer'

  post '/questions/:id/upvote', to: 'questions#upvote', as: 'upvote_question'
  post '/questions/:id/downvote', to: 'questions#downvote', as: 'downvote_question'

  post '/answers/:id/upvote', to: 'answers#upvote', as: 'upvote_answer'
  post '/answers/:id/downvote', to: 'answers#downvote', as: 'downvote_answer'

  devise_for :users
  get 'home/index'
  root 'questions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable

  validates :body, presence: true
  validates_associated :user, :question
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Answer.find(params[:answer_id])
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_question, only: [:create]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  def upvote
    session[:return_to] ||= request.referer

    if current_user.voted_as_when_voted_for @answer # if user has liked this answer, unlike it
      @answer.unliked_by current_user
    else
      @answer.liked_by current_user # otherwise, like it
    end
    redirect_to session.delete(:return_to)
  end

  def downvote
    session[:return_to] ||= request.referer

    unless (current_user.voted_as_when_voted_for @answer) === false # if user has disliked this answer, undislike it
      @answer.disliked_by current_user
    else # if user has not liked nor disliked, dislike it
      @answer.undisliked_by current_user
    end
    redirect_to session.delete(:return_to)
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = @question.answers.new answer_params
    @answer.user = current_user
    @answer.score = 0

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_question
      @question = Question.find(params[:question_id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer_details.erb
<div class="container-fluid no-gutters answer">
  <div class="row">
    <div class="col-1 answer-score">
      <div class="container score">

        <%= render 'layouts/score', votable: answer %>

        <% if current_user === @question.user %>
          <%= button_to [:choose, @question, answer], { class: ((answer.chosen) ? 'answer-chosen' : 'answer-choose') } do %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% end %>
        <% elsif answer.chosen %>
          <div class="container answer-chosen">
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          </div>
        <% end %>

      </div>
    </div>
    <div class="col-7 answer-body">
      <div class="row">
        <%= simple_format(answer.body) %>
      </div>
      <div class="row justify-content-end">
        <div class="col-5 answer-author">
          respondido em <%= answer.created_at %>
          <br>
          <span class="text-primary">
            <%= answer.user.email %>
          </span>
          <%= "- #{answer.user.major} (#{answer.user.year}.#{answer.user.semester})" %>
        </div>
      </div>
    </div>
    <div class="col-4 answer-comments">
      <%# comments on this answer %>
      <%= render 'comments/comments', commentable: answer %>
    </div>
  </div>
</div>

app/views/answers/_answers.erb
<h4 class="divide">
  <%= question.answers.length %>
  <%= question.answers.length === 1 ? "Resposta" : "Respostas" %> <%# pluralização correta %>
</h4>

<% if question.chosen_answer != nil %>
  <%= render 'answers/answer_details', answer: question.chosen_answer %>
<% end %>

<% question.answers.order(:cached_votes_score).reverse.each do |answer| %>
  <% if !answer.chosen %>
    <%= render 'answers/answer_details', answer: answer %>
  <% end %>
<% end %>

<br>

<%# create new answer to this question %>
<%= render 'answers/form', question: @question %>

app/views/answers/_form.html.erb
<h4>Sua Resposta</h4>

<%= form_for [question, Answer.new], html: { autocomplete: "off" } do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "new-answer", required: true %>
  </div>

  <div class="actions">
    <%= f.submit "Responder" %>
  </div>

  <div class="guidelines">
    <%= link_to "Como escrever uma boa resposta (stack overflow)", "https://stackoverflow.com/help/how-to-answer" %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.body %></td>
        <td><%= answer.score %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>Score:</strong>
  <%= @answer.score %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>